In [1]:
import numpy as np
import pandas as pd

In [7]:
data = pd.read_csv(r"C:\Users\exam2\Downloads\text_classification.csv")
data

                                    text status
0               this is an amazing place    pos
1     I feel very good about these beers    pos
2                   this is my best work    pos
3                   what an awesome view    pos
4          I do not like this restaurant    neg
5               I am tired of this stuff    neg
6                 I can't deal with this    neg
7                   he is my sworn enemy    neg
8                    my boss is horrible    neg
9               this is an awesome place    pos
10  I donot like the taste of this juice    neg
11                       I love to dance    pos
12     I am sick and tired of this place    neg
13                  what a great holiday    pos
14        that is a bad locality to stay    neg
15        we will have good fun tomorrow    pos
16      I went to my enemy's house today    neg
17                  I love this sandwich    pos

In [8]:
#splitting the date
train,test = data[:],data[14:]
#extract vocabulary from training
vocabulary = []
for text in train['text']:
    text = text.lower()
    words = text.split()
    for word in words:
        if word not in vocabulary:
            vocabulary.append(word)
print(vocabulary)

['this', 'is', 'an', 'amazing', 'place', 'i', 'feel', 'very', 'good', 'about', 'these', 'beers', 'my', 'best', 'work', 'what', 'awesome', 'view', 'do', 'not', 'like', 'restaurant', 'am', 'tired', 'of', 'stuff', "can't", 'deal', 'with', 'he', 'sworn', 'enemy', 'boss', 'horrible', 'donot', 'the', 'taste', 'juice', 'love', 'to', 'dance', 'sick', 'and', 'a', 'great', 'holiday', 'that', 'bad', 'locality', 'stay', 'we', 'will', 'have', 'fun', 'tomorrow', 'went', "enemy's", 'house', 'today', 'sandwich']

In [9]:
#make the table for both negative and positive
positive_set = train[train['status']=='pos']
negative_set = train[train['status']=='neg']
negative_set

                                    text status
4          I do not like this restaurant    neg
5               I am tired of this stuff    neg
6                 I can't deal with this    neg
7                   he is my sworn enemy    neg
8                    my boss is horrible    neg
10  I donot like the taste of this juice    neg
12     I am sick and tired of this place    neg
14        that is a bad locality to stay    neg
16      I went to my enemy's house today    neg

In [10]:
#term frequency matrix for positive documents
positive_data = {}
for text,index in zip(positive_set['text'],positive_set.index):
    positive_data[index] = []
    terms = text.lower().split()
    for word in vocabulary:
        positive_data[index].append(terms.count(word))
print(positive_set.index)
positive_table = pd.DataFrame(positive_data)
positive_table.index = vocabulary
positive_table = positive_table.T
positive_table

Int64Index([0, 1, 2, 3, 9, 11, 13, 15, 17], dtype='int64')

,this,is,an,amazing,place,i,feel,very,good,about,...,we,will,have,fun,tomorrow,went,enemy's,house,today,sandwich
0,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,1,0,...,1,1,1,1,1,0,0,0,0,0
17,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [11]:
#term frequency matrix for negative documents
negative_data = {}
for text,index in zip(negative_set['text'],negative_set.index):
    negative_data[index] = []
    terms = text.lower().split()
    for word in vocabulary:
        negative_data[index].append(terms.count(word))
print(negative_set.index)
negative_table = pd.DataFrame(negative_data)
negative_table.index = vocabulary
negative_table = negative_table.T
negative_table

Int64Index([4, 5, 6, 7, 8, 10, 12, 14, 16], dtype='int64')

,this,is,an,amazing,place,i,feel,very,good,about,...,we,will,have,fun,tomorrow,went,enemy's,house,today,sandwich
4,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,1,1,1,0

In [12]:
p,n,v = len(positive_set),len(negative_set),len(vocabulary)
p,n,v

(9, 9, 60)

In [16]:
positive_prior = {}
negative_prior = {}
for word in vocabulary:
    positive_prior[word] = round((sum(positive_table[word].to_list())+1)/(p+v),2)
    negative_prior[word] = round((sum(negative_table[word].to_list())+1)/(n+v),2)
result = []
for text in test['text']:
    result.append(predict(text))
print(result)

['neg', 'pos', 'neg', 'pos']

In [15]:
def predict(text):
    terms = text.lower().split()
    pos = 1
    neg = 1
    for term in terms:
        pos *= positive_prior[term]
        neg *= negative_prior[term]
    if pos>= neg:
        return 'pos'
    return 'neg'